### ISSUE TITLE
SPDX-Online-Tools shows error message for License in Japanese

### ISSUE THREAD

**Issue by mandel59** [spdx/license-list-XML#1154]
I've submitted the license text from https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode, and I've got the following message:

>Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 127, in submitNewLicense matchingIds, matchingType = utils.check_spdx_license(licenseText) File "/spdx/src/app/utils.py", line 509, in check_spdx_license licenseText = unicode(licenseText.decode('string_escape'), 'utf-8') UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-16: ordinal not in range(128) 

![image](https://user-images.githubusercontent.com/1079715/100558353-6a7cc100-32f1-11eb-9919-87f500c51e25.png)

**Comment by mandel59** [comment]
License Text: https://gist.github.com/mandel59/527db04e7655f28edb0e8db2bda7c328#file-gistfile1-txt

**Comment by goneall** [comment]
Transferring this issue to the spdx-online-tools repo issues list.
