### ISSUE TITLE
Error on new license request

### ISSUE THREAD

**Issue by freegovinfo** [spdx/license-list-XML#1193]
I just tried to submit a new license via https://tools.spdx.org/app/submit_new_license/ and got the following error> Please advise.

Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 172, in submitNewLicense statusCode = utils.createIssue(licenseAuthorName, licenseName, licenseIdentifier, licenseComments, licenseSourceUrls, licenseHeader, licenseOsi, licenseExamples, licenseRequestUrl, token, urlType) File "/spdx/src/app/utils.py", line 340, in createIssue body = "**1.** License Name: {0}\n**2.** Short identifier: {1}\n**3.** License Author or steward: {2}\n**4.** Comments: {3}\n**5.** Standard License Header: {4}\n**6.** License Request Url: {5}\n**7.** URL(s): {6}\n**8.** OSI Status: {7}\n**9.** Example Projects: {8}".format(licenseName, licenseIdentifier, licenseAuthorName, licenseComments, licenseHeader, licenseRequestUrl, licenseUrls, licenseOsi, licenseExampleUrls) UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 134: ordinal not in range(128)

**Comment by goneall** [comment]
@freegovinfo It looks like it is having trouble encoding one of the fields.  It looks like there is a [section sign](https://charbase.com/00a7-unicode-section-sign) in some of the text in the submittal which is causing the the issue.

If you could remove that, it should work.

**Comment by freegovinfo** [comment]
yes that worked! License submitted.

**Comment by goneall** [comment]
@freegovinfo Good to hear.

I'm going to move this over as an issue in the spdx-online-tools repo to track handling these encoding issue.

Since the error occurred in the issues submittal text processing, we should be able to replace any invalid characters with either a placeholder or translation (e.g. u'\xa7' in this case).
